# -*- coding: utf-8 -*-
"""
luan_giai_objective.py
======================
Tầng LUẬN GIẢI KHÁCH QUAN: mỗi sao ở mỗi cung đều được nêu rõ
ba chiều kích:

  - Bản chất (ban_chat): trạng thái cốt lõi, trung tính.
  - Tích cực  (positive): điểm mạnh thật, có cơ sở.
  - Hạn chế / tiêu cực (negative): điểm yếu thật, không nói giảm nói tránh.

Các sao chính tinh có mô tả riêng (OBJECTIVE_MAIN).
Các sao khác được suy ra từ ẩn nghĩa (STAR_META) và tính chất cung
(CUNG_PROFILE) bằng OBJECTIVE_EXTRA_FOR.

Cách dùng trong engine:
  from luan_giai_objective import objective_for_star_cung
  obj = objective_for_star_cung('tu_vi', 0)
  # -> {'ban_chat':..., 'positive':..., 'negative':..., 'so_sanh':...}
"""

from __future__ import annotations

from scripts.luan_giai_knowledge import CUNG_PROFILE
from scripts.star_knowledge_data import STAR_META


def _o(ban_chat, positive, negative, comparison=None):
    return {
        "ban_chat": ban_chat,
        "positive": positive,
        "negative": negative,
        "comparison": comparison or "",
    }


# --------------------------------------------------------------------------- #
# 14 chính tinh × 12 cung (0=Mệnh, 1=Phụ Mẫu, ..., 11=Huynh Đệ).
# --------------------------------------------------------------------------- #
OBJECTIVE_MAIN = {
    "tu_vi": {
        0: _o("Uy quyền, bản lĩnh, tự tin vào chính mình; thích đứng đầu và được kính nể.",
              "Có tố chất lãnh đạo, quyết đoán, giữ được lề lối; dễ gây ảnh hưởng và được người khác dựa vào.",
              "Tự cao, gia trưởng, khó nghe góp ý; hay cô lập mình, dễ bị a dua mù quáng khi thành công.",
              "Sức mạnh lớn nhưng nếu thiếu người góp ý thẳng sẽ thành kiêu ngạo."),
        1: _o("Cha mẹ có uy thế, gia đình có nền nếp; danh giá gia tộc đè lên đời con.",
              "Được gia thế và tổ tiên hỗ trợ, học được tác phong chỉn chu.",
              "Cha mẹ can thiệp sâu, áp đặt khuôn mẫu; con dễ mang áp lực giữ thể diện.",
              "Phụ thuộc gia đình nhiều; càng sớm độc lập càng tránh bị ràng buộc."),
        2: _o("Phúc khí dày, tinh thần an nhiên, có điều kiện hưởng thụ cao.",
              "Tâm thái vững, biết hưởng phước, có nền tảng tinh thần và phẩm hạnh.",
              "Tự mãn, sống buông thả, dễ xa rời thực tế; ít trải qua khó khăn nên thiếu bản lĩnh rèn giũa.",
              "An nhàn quá mức là mất động lực; cần chủ động đối mặt thử thách."),
        3: _o("Nhà cửa đàng hoàng, cơ nghiệp rộng, được che chở bởi của cải đất đai.",
              "Tài sản ổn định, có chỗ dựa vững; giỏi giữ gìn và làm tăng giá trị cơ nghiệp.",
              "Đặt nặng của cải, dễ đánh đổi tình cảm; càng giàu càng nhiều rủi ro tranh chấp, nợ nần.",
              "Của cải là thế mạnh nhưng cũng là gánh nặng nếu quá tham."),
        4: _o("Sự nghiệp có quyền, có chức, có tiếng nói; dễ thành công ở vị trí dẫn đầu.",
              "Thăng tiến tốt, làm được việc lớn, tạo ảnh hưởng và quyền hành thật.",
              "Ganh đua ác liệt, dễ bị đố kỵ và dèm pha; thích kiểm soát nên kém hợp tác.",
              "Quyền càng cao trách nhiệm càng nặng; cần giữ chữ tín để không đổ."),
        5: _o("Có cấp dưới hùng hậu, bạn bè trong nhóm đều nể; tập thể quy phục mình.",
              "Được người phục vụ, dễ tập hợp lực lượng, có uy trong tập thể.",
              "Người theo hầu có kẻ vì lợi; dễ bị nịnh và mù quáng tin cấp dưới.",
              "Phải phân biệt người trung thực và người xu nịnh; uy quyền dễ sinh phản bội."),
        6: _o("Ra ngoài được trọng vọng, có duyên gặp quý nhân, mở rộng môi trường.",
              "Đi xa có lợi về danh vọng, phát triển mối quan hệ, được người ngoài hỗ trợ.",
              "Càng nổi bật càng dễ bị ganh; đi xa cũng có rủi ro cô đơn và lệ thuộc tiếng tăm.",
              "Nên dùng tiếng tăm làm bàn đạp, không để nó trói buộc."),
        7: _o("Sức khỏe cơ bản vững, nhưng là nơi chứa gánh nặng và sức ép trách nhiệm.",
              "Ít bệnh vặt, có tiềm năng khoẻ lâu; gặp bệnh nhẹ thì chữa được.",
              "Về già sức khoẻ tụt rõ; hay cố chịu đau, bỏ qua bệnh âm thầm.",
              "Cần khám định kỳ dù đang cảm thấy khoẻ."),
        8: _o("Tài chính vững, biết giữ của và làm ăn lớn; là trụ cột kinh tế.",
              "Có của dồi dào, đầu tư có nền tảng, giữ được cơ nghiệp lâu dài.",
              "Tiền nhiều dễ sinh kiêu, keo kiệt với người thân; càng giàu càng dễ mất do tham vọng.",
              "Phải coi tiền là công cụ, không để tiền chi phối lối sống."),
        9: _o("Con cái bản lĩnh, có tương lai; hậu vận có chỗ dựa.",
              "Con có năng lực, tự lập, hiếu thuận theo cách riêng; về già có nơi nương.",
              "Con cái khó gần, ít biểu hiện tình cảm; dễ đứt gãy nếu cha mẹ quá nghiêm hoặc quá bận.",
              "Quyền uy của cha mẹ không thay thế được sự gần gũi."),
        10: _o("Bạn đời đứng đắn, có uy tín; hôn nhân có địa vị xã hội.",
               "Hôn nhân bề thế, có người đồng hành vững vàng, sống có trách nhiệm.",
               "Dễ gia trưởng, áp đặt và muốn kiểm soát bạn đời; tình cảm khô cứng.",
               "Cần tôn trọng và chia sẻ quyết định, không chỉ dựa vào uy quyền."),
        11: _o("Anh em có người ưu tú, thể diện gia đình cao; được anh em nể.",
               "Có người thân giỏi giang, biết giữ thể diện, hỗ trợ nhau khi cần.",
               "Anh em ganh đua, ít cởi mở; quan hệ mang tính nể trọng hơn gần gũi.",
               "Thay vì giành thể diện, nên xây tình cảm chân thật."),
    },
    "thien_co": {
        0: _o("Thông minh, nhạy bén, hay suy nghĩ; sống bằng lý trí và kế hoạch.",
              "Mưu lược, thích nghi tốt, xử lý tình huống giỏi; học nhanh.",
              "Lo nghĩ nhiều, hay nghi ngờ và dễ trì hoãn; thông minh nhưng thiếu kiên quyết.",
              "Trí tuệ là điểm mạnh, nhưng nếu chỉ nghĩ mà không hành sẽ mất cơ hội."),
        1: _o("Cha mẹ tháo vát, khéo lo; con ảnh hưởng tư duy tính toán của gia đình.",
              "Học được sự khôn ngoan, biết cách xoay xở và lo xa.",
              "Cha mẹ khó tính, thiếu thoải mái; con dễ bị áp lực từ kỳ vọng.",
              "Nên nhận tinh hoa của cha mẹ nhưng vẫn có tư duy riêng."),
        2: _o("Tâm trí hoạt động mạnh, thích tìm hiểu; phúc đức thiên về trí tuệ.",
              "Sống nội tâm phong phú, học rộng, có tư duy sâu.",
              "Tinh thần không yên, hay trăn trở; dễ mất ngủ và tự dằn vặt.",
              "Cần học cách buông bỏ suy nghĩ thừa."),
        3: _o("Nhà cửa, tài sản hay thay đổi; cơ nghiệp phụ thuộc vào quyết định.",
              "Biết mua bán, đầu tư bằng trí óc; có cơ hội chuyển hoá tài sản.",
              "Thiếu ổn định, hay thay đổi nhà cửa; dễ sai lầm do tính toán quá nhiều.",
              "Cần rõ ràng giấy tờ và chủ động, không để ý nghĩ mông lung quyết định."),
        4: _o("Sự nghiệp thiên về trí tuệ, nghiên cứu, phân tích; thích ứng nhanh.",
              "Giỏi chuyên môn, tư vấn, nghiên cứu; được tin cậy nhờ đầu óc.",
              "Thích đổi việc, dễ chán, kém kiên trì; công việc càng phức tạp càng dễ rối.",
              "Cần chọn một lĩnh vực theo đuổi lâu dài."),
        5: _o("Bạn bè là người trí thức, hay thay đổi; giúp đỡ bằng lời khuyên.",
              "Có bạn bè thông minh, hiểu biết, hỗ trợ về tri thức.",
              "Quan hệ không ổn định, dễ xa cách; bạn bè có thể lợi dụng trí tuệ.",
              "Nên chọn bạn chân thành hơn bạn giỏi."),
        6: _o("Đi xa có kế hoạch, gặp người thông thái; chuyển biến nhiều.",
              "Cơ hội học hỏi và gặp quý nhân nơi xa; thích nghi nhanh.",
              "Đi xa dễ lo nghĩ và mệt não; môi trường mới kích thích hay động não quá mức.",
              "Cần ổn định tâm lý trước khi thay đổi nơi ở."),
        7: _o("Sức khoẻ bị ảnh hưởng bởi lo nghĩ và căng thẳng.",
              "Nếu biết thư giãn thì trí óc minh mẫn, phát hiện bệnh sớm.",
              "Rất dễ bệnh thần kinh, mất ngủ, dạ dày; lo âu làm bệnh nặng hơn.",
              "Đây là điểm yếu lớn nhất; phải kiểm soát stress."),
        8: _o("Kiếm tiền bằng trí tuệ; tiền đến rồi đi theo tính toán.",
              "Thông minh trong đầu tư, kiếm tiền bằng tri thức và chiến lược.",
              "Hay giữ tiền bạc trong đầu nên dễ sai; tiền dễ hao do thay đổi quyết định.",
              "Cần viết kế hoạch, không để trí óc xoay vòng vô tận."),
        9: _o("Con cái thông minh, thích học; ít con và hay lo cho con.",
              "Con có trí tuệ, học giỏi, hậu vận phát triển.",
              "Lo con quá mức, dễ can thiệp vào cuộc sống con; con có thể xa cách.",
              "Nuôi dưỡng bằng tin tưởng, không phải bằng lo lắng."),
        10: _o("Bạn đời tháo vát, lý trí; mối quan hệ dựa trên suy nghĩ.",
               "Hai người thông minh, cùng bàn kế hoạch, có thể hỗ trợ tài chính.",
               "Hay nghi ngờ, thiếu tin tưởng; cãi nhau nhiều vì lý sự.",
               "Cần học cách lắng nghe hơn là biện luận."),
        11: _o("Anh em giỏi giang, hay thay đổi; quan hệ phụ thuộc mức độ hiểu nhau.",
               "Anh em thông minh, giúp nhau bằng ý kiến.",
               "Anh em xa cách, ít gắn kết; dễ tranh cãi vì ai cũng có chính kiến.",
               "Nên đặt tình thân trên lý sự."),
    },
    "thai_duong": {
        0: _o("Quang minh, hào hiệp, hướng ngoại; muốn toả sáng và giúp đỡ người khác.",
              "Có danh tiếng, nhiệt huyết, hấp dẫn; thành công ở nơi công cộng.",
              "Hay ôm việc, dễ bị lợi dụng lòng tốt; quá đề cao bản thân.",
              "Tốt bụng cần có giới hạn, nếu không sẽ mất năng lượng."),
        1: _o("Cha mẹ hiển vinh, con được lợi từ cha mẹ.",
              "Gia đình có danh tiếng, được cha mẹ lo cho chu toàn.",
              "Áp lực phải nổi bật, thiếu tự do; cha mẹ kỳ vọng lớn.",
              "Danh tiếng gia đình là bàn đạp nhưng không nên thành gông."),
        2: _o("Tinh thần lạc quan, phúc quang minh; thích làm điều tốt.",
              "Có đức, dễ được người quý; tinh thần tích cực.",
              "Dễ mềm lòng, thích can thiệp; phúc đức đôi khi chỉ là lý tưởng.",
              "Cần thực tế hoá lòng tốt, không chỉ bằng lời nói."),
        3: _o("Nhà cửa sáng sủa, đất đai phát triển; của cải dễ mở rộng.",
              "Bất động sản tăng giá, nhà cửa khang trang, có cơ hội phát triển.",
              "Hao phí cho nhà cửa, vay nợ để mở rộng; càng đầu tư càng rủi ro.",
              "Cần giữ dòng tiền, không chạy theo quy mô."),
        4: _o("Sự nghiệp công khai, có danh; hợp công quyền, hành chính, giáo dục.",
              "Thăng quan phát tài, được cấp trên chú ý, có uy tín.",
              "Cạnh tranh và bị soi xét; công việc áp lực, dễ kiệt sức.",
              "Nổi bật càng dễ bị soi; phải giữ phẩm hạnh."),
        5: _o("Bạn bè nhiệt tình, giúp đỡ; tập thể sôi nổi.",
              "Được bạn bè ủng hộ, có sức lan toả, dễ lãnh đạo nhóm.",
              "Bạn bè có thể dựa dẫm mình; bị lợi dụng nhiệt tình.",
              "Chọn bạn dựa trên sự chân thành, không phải nhiệt tình."),
        6: _o("Ra ngoài thành danh, được nhiều người biết; môi trường rộng mở.",
              "Đi xa có lợi về công danh, gặp quý nhân, mở rộng ảnh hưởng.",
              "Được chú ý càng bị chỉ trích; duyên đi xa nhưng cô đơn.",
              "Danh tiếng cần phải đi đôi với nội tâm vững."),
        7: _o("Sức khoẻ tốt, dẻo dai, nhưng dễ bỏ bê khi cuống việc.",
              "Ít bệnh; nếu bệnh thì phục hồi nhanh.",
              "Dễ bệnh mắt, tim mạch, quá tải; chủ quan với sức khoẻ.",
              "Mạnh mẽ không đồng nghĩa với bất tử; cần điều độ."),
        8: _o("Tiền từ công việc minh bạch; tài lộc gắn với danh tiếng.",
              "Thu nhập rõ ràng, có được nhờ uy tín, dễ tăng lộc.",
              "Tiền dễ chi vì hay giúp đỡ, giao phó cho người khác.",
              "Nên phân tách tiền cá nhân với việc làm thiện."),
        9: _o("Con cái sáng sủa, có tương lai; hậu vận sáng.",
              "Con hanh thông, học giỏi, tự tin; có vận sau.",
              "Lo con quá nhiều, kỳ vọng cao; con có thể áp lực.",
              "Điểm mạnh là nhìn xa; điểm yếu là áp đặt tầm nhìn lên con."),
        10: _o("Bạn đời chính trực, cầu tiến; nam mệnh được quý nhân nữ.",
               "Hôn nhân tốt, bạn đời hỗ trợ, vui vẻ.",
               "Dễ bị bạn đời lấn lướt; nữ mệnh có chuyện chồng con.",
               "Phải giữ tiếng nói của mình trong hôn nhân."),
        11: _o("Anh em rộng rãi, vui vẻ; quan hệ hoà hợp.",
               "Anh em hào phóng, đùm bọc, giúp nhau.",
               "Anh em hay vay mượn, lợi dụng lòng tốt; dễ tranh cãi về tiền.",
               "Lòng tốt cũng cần nguyên tắc với người thân."),
    },
    "vu_khuc": {
        0: _o("Cương nghị, nguyên tắc, thực dụng; sống bằng kỷ luật và tiền bạc.",
              "Quyết đoán, có năng lực làm ăn, giữ chữ tín; mạnh về quản lý.",
              "Cứng nhắc, ít cảm xúc, coi trọng đồng tiền hơn con người.",
              "Kỷ luật là sức mạnh nhưng kém linh hoạt sẽ mất người."),
        1: _o("Cha mẹ nghiêm khắc, có trách nhiệm với con.",
              "Được cha mẹ dạy tính tự lập, cần cù, không nợ nần.",
              "Cha mẹ ít cởi mở, nặng về vật chất; con dễ tự ti.",
              "Cần nhận tinh thần cần cù, bỏ sự khắt khe."),
        2: _o("Phúc đức thiên về vật chất và lao động.",
              "Có công cần cù, biết tích luỹ; sống bền bỉ.",
              "Quá coi trọng tiền bạc, thiếu nghỉ ngơi; hưởng thụ kém.",
              "Phúc lành không chỉ là tiền; cần cân bằng."),
        3: _o("Nhà đất có giá trị, biết quản lý cơ nghiệp.",
              "Đầu tư nhà đất tốt, giữ được của cải, tạo nền tảng bền.",
              "Dính mắc vào tài sản, ít chịu chia sẻ; dễ xuống sức vì làm nhà.",
              "Của cải ổn định nếu không tham."),
        4: _o("Sự nghiệp tài chính, kỹ thuật, quản lý; làm việc có kế hoạch.",
              "Giỏi chuyên môn, lương cao, có khả năng lãnh đạo kinh doanh.",
              "Làm việc cứng nhắc, ít chấp nhận mới; thiếu tinh thần sáng tạo.",
              "Cần mở lòng với phương pháp mới."),
        5: _o("Bạn bè đáng tin, biết làm ăn; người giúp đỡ có kỹ năng.",
              "Có quan hệ thực tế, được người giỏi hỗ trợ.",
              "Bạn bè tính toán chuyện tiền bạc; dễ chia tay vì lợi ích.",
              "Phân minh chuyện tiền để giữ tình bạn."),
        6: _o("Đi xa mưu sinh, kiếm tiền; di chuyển nhiều vì sự nghiệp.",
              "Làm ăn nơi xa có lộc, tự lập kinh tế tốt.",
              "Đi lại vất vả, ổn định thấp; tiền kiếm được bằng xương máu.",
              "Cần đầu tư cho nơi ở ổn định."),
        7: _o("Sức khoẻ chịu đựng tốt, nhưng dễ tổn thương xương khớp.",
              "Có sức bền, khoẻ khi lao động, ít mệt nếu biết nghỉ.",
              "Làm việc quá tay, dễ bệnh xương khớp, tai nạn lao động.",
              "Không được ép cơ thể quá sức."),
        8: _o("Tài chính vững, cũng là sao tài bạch; hợp kinh doanh.",
              "Có khả năng giữ của, tăng lộc, làm ăn có lãi.",
              "Hành xử tiền bạc bằng lý trí có thể thiếu tình người; càng giữ càng cô độc.",
              "Tiền cần có mục đích, không phải mục đích."),
        9: _o("Con cái giỏi, tự lập; nhưng ít gần gũi bố mẹ.",
              "Con tự lập tốt, học được kỷ luật, không phụ thuộc.",
              "Cha mẹ nghiêm, con xa cách; thiếu biểu hiện tình cảm.",
              "Ủng hộ con nhưng không kiểm soát con."),
        10: _o("Hôn nhân gắn với trách nhiệm kinh tế; bạn đời thực tế.",
               "Vợ chồng cùng lo toan, ổn định tài chính.",
               "Cãi nhau vì tiền; ít lãng mạn, dễ khô cứng.",
               "Cần dành thời gian lắng nghe cảm xúc."),
        11: _o("Anh em cần cù, cùng làm ăn; quan hệ phụ thuộc lợi ích.",
               "Anh em giỏi nghề, có thể làm ăn chung hiệu quả.",
               "Tranh chấp quyền lợi, ít nhường nhịn; dễ chia rẽ.",
               "Tiền bạc phải rõ ràng giữa anh em."),
    },
    "thien_dong": {
        0: _o("Hiền hoà, nhân từ, thích ổn định; sống dễ chịu, ít muốn đấu tranh.",
              "Dễ mến, có phúc, được người giúp; sống êm ả, có coi trọng tình thân.",
              "Thụ động, dễ dựa dẫm, thiếu tham vọng; bị lợi dụng vì hiền.",
              "Đây là sao phúc nhưng nếu nhu nhược sẽ không tiến được."),
        1: _o("Cha mẹ nhân hậu, dễ chịu; gia đình êm ấm.",
              "Được yêu thương, học cách sống tử tế.",
              "Cha mẹ bao bọc quá mức; con kém bản lĩnh.",
              "Nhận tình thân nhưng vẫn phải tự lập."),
        2: _o("Phúc đức tốt, thích hưởng thụ; an nhàn.",
              "Có phước hưởng, tâm tưởng ổn, sống khoẻ.",
              "Dễ trì trệ, thích an nhàn, thiếu cố gắng.",
              "Hưởng phúc cần có nền tảng làm việc."),
        3: _o("Nhà cửa ấm áp, thoải mái; đất đai nhỏ nhưng đủ.",
              "Chỗ ở êm ái, cuộc sống tiện nghi.",
              "Không chịu mở rộng, thiếu tiến bộ trong tài sản.",
              "An cư lạc nghiệp nhưng nên chủ động hơn."),
        4: _o("Sự nghiệp ổn định, dịch vụ; không thích cạnh tranh.",
              "Hợp nghề chăm sóc, giáo dục, y tế; làm việc nhẹ nhàng.",
              "Ít thăng tiến, dễ bằng lòng, kém quyết đoán.",
              "Nên chọn môi trường ít áp lực nhưng có phát triển."),
        5: _o("Bạn bè tử tế, hiền lành; giúp đỡ vô tư.",
              "Có bạn tốt, quan hệ hoà thuận, được giúp đỡ.",
              "Dễ bị bè bạn lợi dụng; và lại ít nguyên tắc.",
              "Tốt với bạn nhưng đừng đánh đổi chính mình."),
        6: _o("Đi xa hưởng nhàn, gặp người hiền; thoải mái.",
              "Thích nghi nhanh, gặp quý nhân hiền hoà.",
              "Thiếu sự cố gắng; đi xa dễ vừa lòng mà không phát triển.",
              "Cần chủ động hơn thay vì nhân duyên đưa đẩy."),
        7: _o("Sức khoẻ ổn nhưng hay bệnh nhẹ kéo dài.",
              "Bệnh nhẹ, dễ chữa, ít nguy hiểm.",
              "Chủ quan, bệnh mãn tính khó bỏ; dược phẩm cần cẩn thận.",
              "Cần chăm sóc đều đặn, không chờ đau mới lo."),
        8: _o("Tiền đến dễ, tiêu cũng dễ; nhiều duyên lộc.",
              "Dễ được của, nhờ quan hệ và duyên phúc.",
              "Không biết giữ, tiêu phung phí; dễ hết tiền.",
              "Điểm yếu là tiêu xài; cần kế hoạch."),
        9: _o("Con cái hiếu thảo, ngoan ngoãn; hậu vận tốt.",
              "Con hiền, có tình, về già yên vui.",
              "Con phụ thuộc thiếu tính tự lập; dễ buông lơi con.",
              "Dạy con kiên cường, không chỉ hiền lành."),
        10: _o("Hôn nhân hoà thuận, bạn đời hiền; dễ chịu.",
               "Sống thuận hoà, được bạn đời bao dung.",
               "Thiếu chủ động, nghe theo bạn đời; dễ mất tiếng nói.",
               "Hoà thuận tốt nhưng không được từ bỏ chính kiến."),
        11: _o("Anh em đoàn kết, tình cảm.",
               "Anh em hiền, hỗ trợ nhau, không tranh chấp.",
               "Trì hoãn, nhường nhịn thái quá; thiếu độc lập.",
               "Đoàn kết là tốt, nhưng cần ranh giới."),
    },
    "liem_trinh": {
        0: _o("Ngay thẳng, cầu toàn, bộc trực; có khí phách nhưng dễ cực đoan.",
              "Có nguyên tắc, liêm khiết, không chịu khuất phục trước sai trái.",
              "Cứng đầu, nóng giận, dễ xung đột; người khác thấy đáng sợ.",
              "Bản lĩnh lớn nhưng phải kiểm soát thái độ."),
        1: _o("Cha mẹ nghiêm khắc, có thể thành biến cố gia đình.",
              "Học được sự công bằng, chính trực.",
              "Cha mẹ khắt khe, có tranh cãi; con dễ ám ảnh.",
              "Cần hoá giải chuyện gia đình, không để nó điều khiển mình."),
        2: _o("Tâm hồn cường liệt, dễ bị cám dỗ.",
              "Có đam mê, mạnh mẽ; biết theo đuổi.",
              "Dễ bồng bột, sa đà, tâm trạng bất ổn.",
              "Đam mê tốt nhưng thiếu điều độ sẽ phá mình."),
        3: _o("Nhà cửa, đất đai có tranh chấp; của cải có vấn đề pháp lý.",
              "Biết tranh đấu để giữ tài sản.",
              "Dễ kiện tụng, uất ức; mất mát do tranh chấp.",
              "Cần minh bạch giấy tờ từ trước."),
        4: _o("Sự nghiệp hợp luật, công an, quân đội, nghề đặc thù.",
              "Làm việc quyết liệt, có tiếng, có khả năng bảo vệ công lý.",
              "Dễ thăng dễ giáng; bị nổi loạn, xung đột với cấp trên.",
              "Tiết chế để không biến nguyên tắc thành cực đoan."),
        5: _o("Bạn bè mạnh mẽ, có kẻ thù tiềm tàng.",
              "Bạn bè bản lĩnh, quyết đoán.",
              "Dễ kết thù, bị phản bội; mối quan hệ đầy thị phi.",
              "Đừng biến bạn bè thành đối thủ."),
        6: _o("Đi xa có nguy cơ tranh chấp, xung khắc.",
              "Ra ngoài có trải nghiệm, biết đối mặt khó khăn.",
              "Dễ gặp rắc rối, kiện tụng nơi xa.",
              "Cần tránh nói to tiếng và tránh thị phi khi đi xa."),
        7: _o("Sức khoẻ dễ bệnh máu, nội tiết, phụ nữ.",
              "Nếu hiểu cơ thể mình thì phát hiện bệnh sớm.",
              "Dễ bệnh nặng và kéo dài; ít chịu khám.",
              "Phải nghiêm túc với sức khoẻ, không chủ quan."),
        8: _o("Tiền từ nghề đặc thù; dễ rủi ro tài chính.",
              "Kiếm được tiền nhờ chuyên môn và sự quyết liệt.",
              "Tiền dễ mất do tranh chấp, đầu tư cực đoan.",
              "Cần quản lý rủi ro tài chính."),
        9: _o("Con cái bản chất cương, cần dạy dỗ kỹ.",
              "Con mạnh mẽ, có chính kiến.",
              "Con khó bảo, cãi lại; dễ xung đột.",
              "Dạy con bằng sự kiên nhẫn, không phải ức chế."),
        10: _o("Hôn nhân có tranh chấp, dễ chia rẽ.",
               "Tình yêu nồng nhiệt, có trách nhiệm.",
               "Ghen tuông, cãi vã, dễ đổ vỡ.",
               "Tình duyên là điểm yếu rõ nhất; cần tiết chế."),
        11: _o("Anh em cứng đầu, dễ xung khắc.",
               "Anh em có nguyên tắc, không lợi dụng nhau.",
               "Hay thua nhau về cãi vã, ít thân thiết.",
               "Nên xây tình cảm thay vì tranh đúng sai."),
    },
    "thien_phu": {
        0: _o("Trầm ổn, bảo thủ, biết giữ của; sống có nền tảng.",
              "Đáng tin, giỏi quản lý, có tài sản; ít rủi ro.",
              "Hay lùi về an toàn, thiếu đổi mới; dễ trì trệ.",
              "Ổn định là thế mạnh, nhưng cần chấp nhận tính đến rủi ro."),
        1: _o("Cha mẹ có cơ nghiệp, vững vàng.",
              "Được gia thế hỗ trợ, sống có nền tảng.",
              "Cha mẹ bảo thủ, con dễ khuôn mẫu.",
              "Học cái vững của cha mẹ nhưng phải tự đi."),
        2: _o("Phúc đức dồi dào, thực dụng.",
              "Có phúc, biết giữ gìn, hưởng phước có chừng.",
              "Ít thích mạo hiểm, thích an toàn quá mức.",
              "Phúc lành phải dùng đúng chỗ."),
        3: _o("Điền trạch rất tốt: nhiều đất, nhà lớn, cơ nghiệp bền.",
              "Giỏi giữ và tăng tài sản; có kho dự phòng.",
              "Quá say mê giữ của, ít chia sẻ.",
              "Của cải nhiều nhưng cần dùng vào điều có nghĩa."),
        4: _o("Sự nghiệp ổn định, hợp quản lý, ngân hàng, tài chính.",
              "Có chức, có của, được tin cậy; ít thay đổi nghề.",
              "Thiếu sự bứt phá; dễ tự mãn với vị trí hiện có.",
              "Có nền tảng tốt nhưng không được ngủ quên."),
        5: _o("Bạn bè đáng tin; người dưới quyền dễ dùng.",
              "Có bạn tốt, có người giúp việc, hợp tác tốt.",
              "Phụ thuộc người quen, ít kết bạn mới.",
              "Nên mở rộng nhiều hơn để tránh nhóm kín."),
        6: _o("Đi xa có tiền, gây dựng cơ nghiệp nơi khác.",
              "Đi xa hợp kinh doanh, có cơ hội đầu tư.",
              "Đi xa dễ cô đơn, nhớ nhà; thành công muộn.",
              "Cần kế hoạch và sự kiên nhẫn."),
        7: _o("Sức khoẻ tốt nhưng có bệnh mãn tính.",
              "Ổn định, ít tai nạn, sống lâu.",
              "Bệnh kéo dài, ít triệu chứng rõ; dễ bỏ qua.",
              "Điểm yếu là bệnh âm thầm; phải khám định kỳ."),
        8: _o("Tài bạch tốt: có vốn, giữ của, biết đầu tư.",
              "Tiền ổn định, có kho, dư dả.",
              "Keo kiệt, dễ bị lệ thuộc vào tiền.",
              "Tiền là sức mạnh, đừng để nó làm mất tính người."),
        9: _o("Con cái hiền, hậu vận có tài sản.",
              "Con ngoan, sống ổn định; về già được lo.",
              "Con thiếu năng động, chậm tiến.",
              "Nuôi dạy con có chí, không chỉ lo cho con."),
        10: _o("Hôn nhân thực tế, yêu bằng trách nhiệm.",
               "Hôn nhân vững, lo toan cho nhau.",
               "Ít lãng mạn, lãnh cảm; bạn đời dễ cảm thấy bị bỏ rơi.",
               "Cần dành thời gian đổi mới tình cảm."),
        11: _o("Anh em biết giữ gìn; quan hệ ổn định.",
               "Anh em hoà hợp, hỗ trợ công việc.",
               "Anh em ít chia sẻ cảm xúc; dễ dè dặt.",
               "Cần cởi mở hơn để tình thân có chiều sâu."),
    },
    "thai_am": {
        0: _o("Nhạy cảm, nội tâm, thích nghệ thuật; sống bằng cảm xúc.",
              "Có trực giác, sống sâu, được người khác quý mến; có phúc âm.",
              "Dễ đa cảm, buồn phiền, thiếu quyết đoán; bị cảm xúc chi phối.",
              "Mềm mỏng là thế mạnh, nhưng cần vững tâm."),
        1: _o("Mẹ hiền, gia đình tình cảm.",
              "Được mẹ chăm sóc, có tâm hồn ấm áp.",
              "Gắn bó quá sâu, khó tách rời gia đình.",
              "Cần học cách trưởng thành mà vẫn giữ tình thân."),
        2: _o("Tâm linh, nghệ thuật; sống nội tâm.",
              "Có phúc, trực giác tốt, thích cái đẹp.",
              "Hay trầm tư, u sầu; thiếu thực tế.",
              "Tâm linh tốt nhưng cần cân bằng đời sống."),
        3: _o("Nhà cửa đẹp, đất ở phương lành.",
              "Có chỗ ở đẹp, yên ổn.",
              "Hay tiếc, thích nơi kín đáo; khó mở rộng.",
              "Cần cởi mở hơn về tài sản."),
        4: _o("Sự nghiệp văn phòng, giáo dục, y tế; hợp nghề ban đêm.",
              "Làm việc tỉ mỉ, có duyên nghề nữ, giỏi tổ chức.",
              "Thiếu quyết đoán, khó thăng tiến ở môi trường cạnh tranh.",
              "Chọn môi trường phù hợp để phát huy."),
        5: _o("Bạn bè nữ giúp đỡ; quan hệ nhẹ nhàng.",
              "Có bạn tốt, được phụ nữ quý, giữ quan hệ.",
              "Bạn bè nhạy cảm, dễ tổn thương.",
              "Cần thẳng thắn hơn để tránh hiểu lầm."),
        6: _o("Ra ngoài gặp quý nhân nữ; đi xa có duyên tài vận.",
              "Đi xa có lộc, dễ được hỗ trợ.",
              "Đi xa dễ nhớ nhà, buồn; chịu ảnh hưởng phụ nữ.",
              "Đừng để tình cảm phá vỡ cơ hội."),
        7: _o("Sức khoẻ tâm lý và sinh sản; dễ tổn thương tinh thần.",
              "Có trực giác, phát hiện bệnh sớm.",
              "Bệnh tâm lý, khí huyết, phụ nữ nguy cơ sinh sản.",
              "Sức khoẻ là điểm cần chú ý nhất."),
        8: _o("Tài lộc âm thầm, có của từ phụ nữ, gia đình.",
              "Có tiền nhẹ nhàng, hợp nghề nữ.",
              "Tiền đến rồi đi; dễ mất vì yếu mềm.",
              "Cần chủ động tài chính."),
        9: _o("Con cái ngoan, đặc biệt con gái.",
              "Con hiền, có tình, tương lai ổn định.",
              "Con hay buồn, nhạy cảm; mẹ lo nhiều.",
              "Dạy con mạnh mẽ tinh thần."),
        10: _o("Hôn nhân tình cảm sâu; bạn đời thùy mị.",
               "Tình cảm chân thành, được bạn đời yêu quý.",
               "Ghen, lo lắng, dễ tổn thương.",
               "Cần tin tưởng hơn là nghi ngờ."),
        11: _o("Anh em tình cảm, chiều chuộng.",
               "Anh em yêu thương, hỗ trợ.",
               "Dễ bi quan, xa cách khi có hiểu lầm.",
               "Nên chia sẻ thẳng thắn."),
    },
    "tham_lang": {
        0: _o("Ham muốn mạnh, thông minh, năng động; đa tài.",
              "Có tài, nhạy bén, thích khám phá; làm được nhiều việc.",
              "Dễ sa đà, ham chơi, thiếu bền chí; hình thành thói xấu.",
              "Tham lang là năng lượng lớn; nếu không trị sẽ tự huỷ."),
        1: _o("Cha mẹ bận rộn, đa tài.",
              "Học được sự năng động.",
              "Cha mẹ thiếu chăm sóc, dễ sa ngã nếu không lo.",
              "Cần tự giác hơn khi thiếu giám sát."),
        2: _o("Phúc đức thiên về hưởng thụ, tình dục, đào hoa.",
              "Có khả năng thưởng thức, nhiều thú vui.",
              "Dễ dâm, ăn chơi, tổn phúc.",
              "Đam mê cần có giới hạn."),
        3: _o("Nhà cửa hoa lệ, tiêu cho đất đai.",
              "Sang trọng, hợp thẩm mỹ.",
              "Tiêu khoản lớn cho nhà, vay mượn.",
              "Đầu tư nhà đất cần tính toán, không chạy theo ham hố."),
        4: _o("Sự nghiệp thương mại, giải trí, nghệ thuật.",
              "Giỏi buôn bán, làm nghề có tiếng, thích mạo hiểm.",
              "Dễ đổi dạ, làm nhiều mà thiếu tâm huyết.",
              "Cần một hướng đi rõ ràng."),
        5: _o("Bạn bè vui vẻ, ham chơi.",
              "Có bạn, giao tiếp tốt.",
              "Bạn xấu lôi kéo; tiền bạc dễ hao do bạn bè.",
              "Chọn bạn kỹ."),
        6: _o("Đi xa nhiều cơ hội ham vui.",
              "Ra ngoài có duyên, phát triển quan hệ.",
              "Dễ sa đà, thiếu kế hoạch khi đi xa.",
              "Cần kỷ luật hành trình."),
        7: _o("Bệnh do ăn chơi; sức khoẻ bị tổn.",
              "Nếu biết chăm thì phục hồi.",
              "Dễ bệnh gan, mỡ máu, xã hội.",
              "Đây là điểm yếu thật; phải dừng đúng lúc."),
        8: _o("Tiền nhiều, tiêu mạnh; dễ thất lộc.",
              "Kiếm tiền nhanh, làm ăn lớn.",
              "Tiêu xài không kiểm soát, dễ nợ.",
              "Tài chính là điểm yếu nếu không kỷ luật."),
        9: _o("Con cái năng động, có tài.",
              "Con có năng lực, dám làm.",
              "Con hư hỏng nếu không dạy; dễ xa.",
              "Cần phương pháp giáo dục nghiêm túc."),
        10: _o("Hôn nhân thú vị nhưng dễ ghen, đào hoa.",
               "Tình yêu nồng, có sức hút.",
               "Dễ ngoại tình, dễ ghen; hôn nhân nhiều sóng gió.",
               "Phải trung thành và kiềm chế."),
        11: _o("Anh em hoạt bát, ham vui.",
               "Anh em giỏi nghề, vui vẻ.",
               "Anh em ham chơi, dễ bị lôi kéo.",
               "Nên có ranh giới."),
    },
    "cu_mon": {
        0: _o("Đa nghi, miệng lưỡi sắc bén; tranh luận giỏi.",
              "Thông minh, có tài thuyết phục; biết chất vấn, tìm ra vấn đề.",
              "Dễ cãi, hay soi mói, tự ti may ra khoe khoang; tạo thị phi.",
              "Miệng là lưỡi dao; phải cẩn ngôn."),
        1: _o("Cha mẹ nói nhiều, khó khăn thời trẻ.",
              "Học được khả năng diễn đạt.",
              "Cha mẹ hay cãi, gia đình căng thẳng.",
              "Cần đối thoại không tranh cãi."),
        2: _o("Tâm trí nhiều trăn trở, thích điều tra.",
              "Sâu sắc, hay tìm hiểu.",
              "Nghi ngờ cuộc sống, dễ tiêu cực.",
              "Cần nhìn nhận cuộc sống tích cực."),
        3: _o("Nhà cửa ồn ào, hay thay đổi.",
              "Biết đàm phán, thương lượng.",
              "Vấn đề pháp lý, tranh chấp nhà đất.",
              "Giấy tờ phải rõ ràng."),
        4: _o("Sự nghiệp luật, báo, giáo dục; dùng miệng kiếm ăn.",
              "Có tiếng nói chuyên môn, đấu tranh tốt.",
              "Thường gây tranh cãi, dễ bị ghét.",
              "Nghề miệng lưỡi có lộc nhưng cũng có hoạ."),
        5: _o("Bạn bè miệng miệng, thị phi.",
              "Giỏi giao tiếp, nói chuyện hấp dẫn.",
              "Bạn bè hay bàn tán, xích mích.",
              "Chọn bạn tránh người lắm lời."),
        6: _o("Đi xa gặp lời thị phi.",
              "Ra ngoài có thông tin, nói chuyện lợi thế.",
              "Dễ bị hiểu lầm, tranh luận, rắc rối.",
              "Khi đi xa cẩn ngôn."),
        7: _o("Bệnh hô hấp, thần kinh; dễ căng thẳng.",
              "Nếu biết thư giãn, tỉnh táo.",
              "Đau dạ dày, mio, mất ngủ.",
              "Sức khoẻ gắn liền với cảm xúc."),
        8: _o("Tiền từ nghề miệng lưỡi; dễ tranh cãi tiền.",
              "Khéo xoay tiền, thương lượng.",
              "Nợ, tranh chấp; dễ bị kiểm tra.",
              "Quản lý tài chính kỹ."),
        9: _o("Con cái hay cãi; có tài nói.",
              "Con có khẩu tài, nhanh nhẹn.",
              "Con khó bảo, hay chống đối.",
              "Dạy con bằng gương mẫu."),
        10: _o("Hôn nhân cãi vã nhiều.",
               "Hai người cùng thảo luận.",
               "Ghen, nghi ngờ, tranh cãi.",
               "Tình duyên cần nhường nhịn."),
        11: _o("Anh em có ý kiến mạnh, tranh nhau.",
               "Anh em giỏi tranh luận.",
               "Anh em chia rẽ, ít hoà hợp.",
               "Cần xây tình cảm trước lý sự."),
    },
    "thien_tuong": {
        0: _o("Phong thái chuẩn mực, biết lắng nghe; sống có trách nhiệm.",
              "Đáng tin, thuyết phục, có sức hút xã giao.",
              "Dễ bị lệ thuộc vào sự công nhận; thiếu sự quyết đoán khi cần.",
              "Khiêm tốn là đẹp, nhưng phải có cương quyết."),
        1: _o("Cha mẹ chuẩn mực, dìu dắt khéo.",
              "Học được kỹ năng, có người dẫn dắt.",
              "Cha mẹ có thể quá khắt khe.",
              "Nhận sự dạy dỗ nhưng vẫn là chính mình."),
        2: _o("Tinh thần ổn định, phẩm hạnh.",
              "Sống có đức, tâm an.",
              "Dễ tự mãn, không chịu thử thách.",
              "Cần rèn luyện thêm bản lĩnh."),
        3: _o("Nhà cửa đàng hoàng, có người trông.",
              "Tài sản ổn, người giúp việc tốt.",
              "Thiếu sự sở hữu rõ ràng.",
              "Cần nắm quyền sở hữu."),
        4: _o("Sự nghiệp quan chức, đoàn thể, tư vấn.",
              "Có chức, được tin, đường hoạt bát.",
              "Làm dưới người, ít tự chủ.",
              "Cần tự lập hơn."),
        5: _o("Bạn bè giúp đỡ, có người giỏi.",
              "Có nhóm hỗ trợ mạnh.",
              "Bạn bè dựa vào mình, thiếu độc lập.",
              "Nên có ranh giới."),
        6: _o("Ra ngoài gặp quý nhân, xây mối.",
              "Đi xa được giúp, phát triển quan hệ.",
              "Thiếu quyết đoán khi đi xa.",
              "Cần tự tin."),
        7: _o("Bệnh nhẹ, điều trị nhanh.",
              "Ít bệnh; bệnh có y tế tốt.",
              "Bỏ bê sức khoẻ vì bận việc.",
              "Vẫn cần khám định kỳ."),
        8: _o("Tiền ổn định, thích giúp đỡ.",
              "Hợp làm dịch vụ, có thu nhập ổn.",
              "Tiêu cho người khác; dễ thiếu.",
              "Cần giữ một phần cho mình."),
        9: _o("Con cái ngoan, có năng lực.",
              "Con hiểu chuyện, dạy dỗ được.",
              "Con dễ phụ thuộc.",
              "Khuyến khích con tự lập."),
        10: _o("Hôn nhân lịch sự, hỗ trợ nhau.",
               "Bạn đời chuẩn mực, hợp tác tốt.",
               "Thiếu đam mê, cuộc sống tẻ nhạt.",
               "Cần thêm cảm xúc."),
        11: _o("Anh em chuẩn mực, hoà thuận.",
               "Anh em đàng hoàng, giúp nhau.",
               "Ít gần gũi, thiếu chiều sâu.",
               "Nên quan tâm hơn."),
    },
    "thien_luong": {
        0: _o("Hiền từ, hay giúp người; sống có đạo đức.",
              "Được người quý, có phúc; hoá giải khó khăn.",
              "Hay tốn kém vì giúp người; dễ bị lợi dụng.",
              "Tốt bụng cần có nguyên tắc."),
        1: _o("Cha mẹ phúc hậu, chịu khó.",
              "Được yêu thương, sống có đức.",
              "Cha mẹ vất vả; gia đình bo bo.",
              "Cần biết cách hưởng phước."),
        2: _o("Phúc đức rất tốt; an lành.",
              "Được phúc báo, tâm an.",
              "Dễ lười biếng, thích nhàn.",
              "Phước phải gìn giữ."),
        3: _o("Nhà cửa an lành, có phúc tổ.",
              "Có cơ nghiệp yên ấm.",
              "Thiếu phát triển.",
              "Cần tận dụng."),
        4: _o("Sự nghiệp giáo, y, luật, tư pháp.",
              "Nghề có đức, được kính trọng.",
              "Thu nhập thấp, ít tham vọng.",
              "Nghề help người cần biết kiếm tiền."),
        5: _o("Bạn bè đáng tin, hay giúp.",
              "Có bạn tốt, quý nhân.",
              "Bạn bè lợi dụng lòng tốt.",
              "Chọn bạn cẩn thận."),
        6: _o("Đi xa gặp quý nhân, hoá giải nạn.",
              "Đi xa được cứu giúp.",
              "Hay lo xa, sợ đi.",
              "Cần mạnh dạn."),
        7: _o("Bệnh dễ khỏi; gặp y giỏi.",
              "Có phúc, bệnh nhẹ.",
              "Chủ quan, bỏ qua bệnh.",
              "Cần khám kỹ khi có dấu hiệu."),
        8: _o("Tài chính vừa phải, hay giúp người.",
              "Có phúc, lòng tốt.",
              "Thiếu tiền, dễ cho vay.",
              "Quản lý tài chính."),
        9: _o("Con cái hiếu, hậu vận tốt.",
              "Con hiếu thảo, sống hiền.",
              "Con dễ nhút nhát, phụ thuộc.",
              "Rèn con bản lĩnh."),
        10: _o("Vợ chồng từ tế, sống lâu.",
               "Hôn nhân bền, yêu thương.",
               "Có thể kiệt sức vì lo cho nhà.",
               "Cần tự chăm."),
        11: _o("Anh em hiếu thuận, giúp đỡ.",
               "Anh em hiền, hoà thuận.",
               "Anh em ít mạnh mẽ.",
               "Nên cùng phát triển."),
    },
    "that_sat": {
        0: _o("Quyết đoán, mạnh mẽ, độc lập; dám làm.",
              "Có bản lĩnh, nghị lực, tự lập, thích chinh phục.",
              "Nóng nảy, cố chấp, thiếu kiên nhẫn; dễ tự cô lập.",
              "Sức mạnh lớn nhưng dễ phá vỡ quan hệ."),
        1: _o("Cha mẹ mạnh mẽ, xa cách.",
              "Học được sự độc lập.",
              "Mối quan hệ gia đình lạnh nhạt.",
              "Cần gần gũi cha mẹ."),
        2: _o("Tâm tính mạnh, hay lo.",
              "Có sự dứt khoát.",
              "Nội tâm dễ bất an.",
              "Cần rèn sự bình tĩnh."),
        3: _o("Nhà cửa có thay đổi lớn, phá xây.",
              "Biết đổi mới tài sản.",
              "Mất của, thay đổi đột ngột.",
              "Đầu tư bất động sản cần cẩn thận."),
        4: _o("Sự nghiệp bứt phá; hợp quân, công an, chính trị.",
              "Làm việc mạnh mẽ, nhanh, có tiếng.",
              "Áp lực, xung đột; dễ thất bại vì nóng.",
              "Cần kiểm soát cảm xúc."),
        5: _o("Bạn bè mạnh, dễ dẫn dắt.",
              "Nhóm mạnh, quyết đoán.",
              "Bạn bè thù địch, dễ tranh chấp.",
              "Chọn đồng minh cẩn thận."),
        6: _o("Đi xa gặp cơ hội nhưng rủi ro.",
              "Có thể thành công lớn nơi xa.",
              "Tai nạn, rủi ro khi đi xa.",
              "Chuẩn bị kỹ càng."),
        7: _o("Dễ tai nạn, chấn thương.",
              "Nếu cẩn thận thì là nguồn rèn luyện.",
              "Nguy cơ thương tích, rủi ro sức khoẻ.",
              "Đây là điểm yếu nghiêm trọng nhất."),
        8: _o("Kinh doanh lớn, sóng gió.",
              "Có cơ hội làm giàu nhanh.",
              "Rủi ro tài chính cao.",
              "Cần quản lý rủi ro."),
        9: _o("Con cái mạnh, ít gần.",
              "Con tự lập, mạnh mẽ.",
              "Con xa cách, khó dạy.",
              "Dành thời gian và tình cảm cho con."),
        10: _o("Hôn nhân nóng gắt, bạn đời độc lập.",
               "Tình yêu mãnh liệt.",
               "Dễ cãi nhau, căng thẳng.",
               "Cần kiềm chế."),
        11: _o("Anh em ganh nhau, tự lập.",
               "Anh em mạnh mẽ, không dựa dẫm.",
               "Thiếu gắn kết, chia rẽ.",
               "Bỏ bớt ganh đua."),
    },
    "pha_quan": {
        0: _o("Táo bạo, đổi mới, tự do; không thích gò bó.",
              "Có khí phách, dám phá cái cũ, có sức bứt phá lớn.",
              "Bốc đồng, dễ phá hoại, hay thay đổi; thiếu kiên định.",
              "Tài năng lớn, nhưng kỷ luật là thứ bắt buộc."),
        1: _o("Cha mẹ lăn lộn, đổi thay.",
              "Học được sự tháo vát.",
              "Gia đình bất ổn, xa cách.",
              "Cần tạo nền tảng cho chính mình."),
        2: _o("Tinh thần bứt phá, nhiều bước ngoặt.",
              "Sống năng động, không sợ thay đổi.",
              "Nội tâm bất an, dễ sốc.",
              "Cần nơi tựa vững."),
        3: _o("Nhà cửa phá rồi xây.",
              "Biết đầu tư táo bạo.",
              "Mất của, thay đổi nơi ở liên tục.",
              "Cân nhắc trước khi phá cái cũ."),
        4: _o("Sự nghiệp khởi nghiệp, nghề mới.",
              "Táo bạo, đổi mới, thành công lớn.",
              "Thất bại đột ngột, thường xuyên đổi việc.",
              "Cần chọn một con đường rồi bám theo."),
        5: _o("Bạn bè tự do, dễ lợi dễ mất.",
              "Có nhóm mở, không ràng buộc.",
              "Bạn bè thay đổi, dễ phản bội.",
              "Chọn bạn kỹ."),
        6: _o("Đi xa làm ăn táo bạo.",
              "Cơ hội lớn nơi xa.",
              "Rủi ro nguy hiểm, mất mát.",
              "Cần kế hoạch."),
        7: _o("Dễ chấn thương, đau đớn.",
              "Có sự chịu đựng.",
              "Nguy cơ tai nạn, bệnh cấp tính.",
              "Đây là điểm yếu nghiêm trọng."),
        8: _o("Tiền vào nhanh, mất nhanh.",
              "Đầu tư lớn, lợi nhuận cao.",
              "Phá sản, nợ nần nếu thiếu kỷ luật.",
              "Tài chính là rủi ro lớn nhất."),
        9: _o("Con tự lập, hay thay đổi.",
              "Con mạnh dạn, độc lập.",
              "Con xa, khó nuôi.",
              "Nuôi dạy con có định hướng."),
        10: _o("Hôn nhân nhiều sóng gió.",
               "Tình yêu mãnh liệt, thú vị.",
               "Dễ ly hôn, thay đổi.",
               "Cần cam kết và bình tĩnh."),
        11: _o("Anh em phiêu bạt, xa nhau.",
               "Tự lập, ít dựa dẫm.",
               "Thiếu gắn kết.",
               "Nên xây tình thân."),
    },
}


# --------------------------------------------------------------------------- #
# Hàm sinh obj khách quan cho mọi sao (kể cả phụ tinh).
# --------------------------------------------------------------------------- #
# Nhóm từ khoá phủ định dùng cho hung tinh.
_STRENGTH_NATURAL = {
    "tốt": ("Điểm mạnh thật: có ẩn phúc, dễ thành công nếu biết tận dụng.",),
    "xấu": ("Điểm có thể dùng: biết tiết chế và đặt đúng cung, có thể chuyển thành kinh nghiệm hoặc nghị lực.",),
    "xấu-trung": ("Điểm có thể dùng: không hẳn xấu; nếu được tiết chế, trở thành nghị lực.",),
    "trung": ("Điểm trung tính: tạo ra tính cách hai chiều, phụ thuộc cách vận dụng.",),
}
_LIMIT_NATURAL = {
    "tốt": ("Điểm yếu: dễ tự mãn, lệ thuộc quý nhân, lơ là thực tế; khi quá tốt dễ sinh kiêu và mất cảnh giác.",),
    "xấu": ("Điểm yếu thật: đề phòng thất bại, tổn thất, tai nạn, thị phi; không được coi thường.",),
    "xấu-trung": ("Điểm yếu thật: bản chất hung, dễ tạo rủi ro; cần biết kiềm chế và có kế hoạch phòng ngừa.",),
    "trung": ("Điểm yếu: thiên về lưỡng lự, khó quyết, dễ bỏ lỡ; không ổn định.",),
}


def objective_for_star_cung(star_key: str, cung_index: int) -> dict:
    if star_key in OBJECTIVE_MAIN and cung_index in OBJECTIVE_MAIN[star_key]:
        return OBJECTIVE_MAIN[star_key][cung_index]
    meta = STAR_META.get(star_key)
    cung_name, cung_domain, cung_pos, cung_neg, _advice = CUNG_PROFILE[cung_index]
    if not meta:
        return _o(
            "Thông tin tổng hợp về sao tại cung này.",
            "Xét trong tổng thể lá số; cần đối chiếu đắc hãm và hội chiếu.",
            "Không có mặt tiêu cực rõ vì thiếu dữ liệu; cần xem cặp sao liên quan.",
        )
    name = meta["name"]
    nature = meta["nature"]
    ban_chat = f"{name} tại cung {cung_name}: {meta['general']} Cung {cung_name} liên quan {cung_domain.lower()}."
    positive = f"Tích cực nếu đắc vận: {_STRENGTH_NATURAL.get(nature, _STRENGTH_NATURAL['trung'])[0]} Đặt đúng cung {cung_name}, tăng khả năng hoàn thành {cung_domain.lower()}."
    negative = f"Hạn chế/tiêu cực: {_LIMIT_NATURAL.get(nature, _LIMIT_NATURAL['trung'])[0]} Tại cung {cung_name}, dễ lộ rõ mặt này trong {cung_domain.lower()}."
    return _o(ban_chat, positive, negative)
