# -*- coding: utf-8 -*-
"""
star_knowledge_data.py
======================
Mô tả kiến thức "Sao ở Cung" cho kho Tử Vi 518.400 lá số.

Cấu trúc:
  - `CUNG_ESSENCE`  : ý nghĩa 12 cung theo thứ tự TƯƠNG ĐỐI từ cung Mệnh
                      (0=Mệnh, 1=Phụ Mẫu, ..., 11=Huynh Đệ).
  - `STAR_META`     : ẩn nghĩa gốc của từng sao (mã cột `pos_*`), loại sao,
                      tính chất (tốt/xấu/trung), "cung" vận hành chính.
  - `DETAIL_MAIN`   : mô tả riêng 14 chính tinh × 12 cung (168 mục).
  - `DETAIL_EXTRA`  : mô tả riêng thêm một số phụ tinh quan trọng.

Người dùng truy vấn theo (star_key, cung_index) với cung_index là vị trí TƯƠNG
ĐỐI so với cung Mệnh. Trong chart, cung_index = (pos_star - menh_cung) % 12.
"""

from __future__ import annotations

# --------------------------------------------------------------------------- #
# 12 cung theo thứ tự tương đối (từ cung Mệnh, đi thuận chiều kim đồng hồ).
# --------------------------------------------------------------------------- #
CUNG_ESSENCE = {
    0: ("Mệnh", "Bản thân, tính cách, năng lực, định mệnh và cách nhìn đời của đương số."),
    1: ("Phụ Mẫu", "Cha mẹ, trưởng bối, tổ tiên, môi trường gia đình, học vấn gốc và thời trẻ."),
    2: ("Phúc Đức", "Phúc khí, tinh thần, tâm linh, hưởng thụ, phẩm hạnh và hậu phúc của đương số."),
    3: ("Điền Trạch", "Nhà cửa, đất đai, tổ nghiệp, tài sản cơ nghiệp, công việc ổn định."),
    4: ("Quan Lộc", "Sự nghiệp, công danh, quyền lực, học hành chuyên môn, cơ quan, nghề nghiệp."),
    5: ("Nô Bộc", "Bạn bè, đồng nghiệp, người dưới quyền, tập thể, quan hệ xã hội gần."),
    6: ("Thiên Di", "Xuất ngoại, đi xa, người ngoài, công việc xa nhà, môi trường giao tiếp rộng."),
    7: ("Tật Ách", "Sức khoẻ, bệnh tật, tai nạn, khó khăn, lo âu về thể chất và tinh thần."),
    8: ("Tài Bạch", "Tiền bạc, tài chính, thu nhập, kinh doanh, tiêu xài và khả năng giữ của."),
    9: ("Tử Tức", "Con cái, hậu vận, sự tiếp nối, cảm xúc nuôi dạy, tài sản để lại đời sau."),
    10: ("Phu Thê", "Hôn nhân, vợ chồng, tình duyên, người bạn đời, quan hệ phối ngẫu."),
    11: ("Huynh Đệ", "Anh chị em, bạn ruột, đồng môn, sự cạnh tranh gần và quan hệ bình đẳng."),
}

# Tên cung chỉ số 0..11 dùng khi in.
CUNG_NAMES = [CUNG_ESSENCE[i][0] for i in range(12)]


def _meta(name, group, nature, general):
    return {"name": name, "group": group, "nature": nature, "general": general}


STAR_META = {
    # ------------------------- 14 chính tinh --------------------------
    "tu_vi": _meta("Tử Vi", "chính tinh", "tốt",
                   "Đế tinh, chủ quyền uy và thuộc Thổ; biểu trưng uy tín, quý phái, thông minh, có bề thế."),
    "thien_co": _meta("Thiên Cơ", "chính tinh", "tốt",
                      "Mưu lược, thông minh, thích nghi, sâu sắc và lo nghĩ; thuộc Mộc."),
    "thai_duong": _meta("Thái Dương", "chính tinh", "tốt",
                        "Mặt trời, chủ quang minh, danh tiếng, hào hiệp, tỏa sáng; thuộc Hỏa."),
    "vu_khuc": _meta("Vũ Khúc", "chính tinh", "tốt",
                     "Sao tài chính, cương nghị, kỷ luật, tháo vát, giỏi kinh doanh; thuộc Kim."),
    "thien_dong": _meta("Thiên Đồng", "chính tinh", "tốt",
                        "Hòa nhã, phúc lành, ổn định, thích hưởng thụ và nhân từ; thuộc Thủy."),
    "liem_trinh": _meta("Liêm Trinh", "chính tinh", "xấu-trung",
                        "Liêm khiết nhưng cũng cứng rắn, bộc trực, dễ xung đột; thuộc Hỏa."),
    "thien_phu": _meta("Thiên Phủ", "chính tinh", "tốt",
                       "Kho tàng, phú quý, bảo thủ, ôn hoà, giữ gìn cơ nghiệp; thuộc Thổ."),
    "thai_am": _meta("Thái Âm", "chính tinh", "tốt",
                     "Mặt trăng, chủ tình cảm, nội tâm, tài lộc âm thầm, dịu dàng; thuộc Thủy."),
    "tham_lang": _meta("Tham Lang", "chính tinh", "xấu-trung",
                       "Dục vọng, năng động, thông minh nhưng ham muốn, dễ hoa đàm; thuộc Mộc."),
    "cu_mon": _meta("Cự Môn", "chính tinh", "xấu-trung",
                    "Hàm tàng, đa nghi, có tài ăn nói, hay tranh luận; thuộc Thủy."),
    "thien_tuong": _meta("Thiên Tướng", "chính tinh", "tốt",
                         "Tướng mạo, trí tuệ, trợ giúp, chuẩn mực, bình thản; thuộc Thủy."),
    "thien_luong": _meta("Thiên Lương", "chính tinh", "tốt",
                         "Phúc tinh, cứu giải, trưởng giả, thanh cao, thích phước đức; thuộc Mộc."),
    "that_sat": _meta("Thất Sát", "chính tinh", "xấu-trung",
                      "Quyết đoán, mạnh mẽ, hành động nhanh, dễ nóng và cô độc; thuộc Kim."),
    "pha_quan": _meta("Phá Quân", "chính tinh", "xấu-trung",
                      "Phá cựu lập tân, tự do, bất khuất, lớn lao nhưng hay thay đổi; thuộc Thủy."),
    # ------------------------- vòng Trường Sinh --------------------------
    "truong_sinh": _meta("Trường Sinh", "vòng Trường Sinh", "tốt",
                         "Sức sống mới, khởi đầu, sinh cơ, năng lượng tươi trẻ."),
    "duong": _meta("Dưỡng", "vòng Trường Sinh", "tốt", "Nuôi dưỡng, tích tụ, chờ đợi, chăm sóc."),
    "thai": _meta("Thai", "vòng Trường Sinh", "trung", "Hình thành, ấp ủ, tiềm năng, chưa bộc lộ."),
    "tuyet": _meta("Tuyệt", "vòng Trường Sinh", "xấu", "Dứt đoạn, khép lại, tuyệt vọng tạm thời."),
    "mo": _meta("Mộ", "vòng Trường Sinh", "xấu", "Thu tàng, trì trệ, giữ gìn, chôn vùi."),
    "tu": _meta("Tử", "vòng Trường Sinh", "xấu", "Kết thúc một giai đoạn, nguy cơ, hao tổn."),
    "benh": _meta("Bệnh", "vòng Trường Sinh", "xấu", "Suy yếu, khó khăn cản trở, cần nghỉ ngơi."),
    "suy": _meta("Suy", "vòng Trường Sinh", "xấu", "Giảm sút, mỏi mệt, thiếu vững, giai đoạn đi xuống."),
    "de_vuong": _meta("Đế Vượng", "vòng Trường Sinh", "tốt",
                      "Cực thịnh, đầy đủ, quyền lực, thời điểm mạnh nhất."),
    "lam_quan": _meta("Lâm Quan", "vòng Trường Sinh", "tốt",
                      "Thăng tiến, gần quyền, trưởng thành, có cơ hội."),
    "quan_doi": _meta("Quan Đới", "vòng Trường Sinh", "tốt",
                      "Khoác mũ áo, đạt danh hiệu, trưởng thành sớm, nên duyên."),
    "moc_duc": _meta("Mộc Dục", "vòng Trường Sinh", "trung",
                     "Đầu đời, thơ ấu, học hỏi, còn non nớt."),
    # ------------------------- vòng Thái Tuế --------------------------
    "thai_tue": _meta("Thái Tuế", "vòng Thái Tuế", "trung", "Năm tháng, vận hành thời, chủ những thay đổi màu sắc."),
    "thieu_duong": _meta("Thiếu Dương", "vòng Thái Tuế", "tốt", "Sinh khí, tươi sáng, vận khởi tốt."),
    "tang_mon": _meta("Tang Môn", "vòng Thái Tuế", "xấu", "Chuyện tang tóc, lo buồn, gia đạo bất an."),
    "thieu_am": _meta("Thiếu Âm", "vòng Thái Tuế", "trung", "Âm khí, lặng lẽ, chờ thời, chậm mà ấm."),
    "quan_phu": _meta("Quan Phù", "vòng Thái Tuế", "trung", "Quan hệ hành chính, tranh chấp, kiện tụng."),
    "tu_phu": _meta("Tử Phù", "vòng Thái Tuế", "xấu", "Nguy cơ, khó khăn, cần dè chừng."),
    "tue_pha": _meta("Tuế Phá", "vòng Thái Tuế", "xấu", "Phá vỡ kế hoạch, xáo trộn, nhất thời."),
    "long_duc": _meta("Long Đức", "vòng Thái Tuế", "tốt", "Ân đức, quý nhân, phước lành."),
    "bach_ho": _meta("Bạch Hổ", "vòng Thái Tuế", "xấu", "Hung tinh, tai ương đột ngột."),
    "phuc_duc": _meta("Phúc Đức", "vòng Thái Tuế", "tốt", "Phúc khí, may mắn, an nhàn."),
    "dieu_khach": _meta("Điếu Khách", "vòng Thái Tuế", "xấu", "Tang khách, việc buồn, tinh thần nặng."),
    "truc_phu": _meta("Trực Phù", "vòng Thái Tuế", "trung", "Theo dõi, ám ảnh, chậm phát."),
    # ------------------------- vòng Lộc Tồn --------------------------
    "loc_ton": _meta("Lộc Tồn", "vòng Lộc Tồn", "tốt",
                     "Sao tài lộc, tiền bạc, ấm no, mong muốn vật chất được viên mãn."),
    "bac_sy": _meta("Bác Sỹ", "vòng Lộc Tồn", "tốt", "Học vấn, tri thức, trình độ chuyên môn."),
    "luc_sy": _meta("Lực Sỹ", "vòng Lộc Tồn", "tốt", "Người hộ trợ, sức khỏe, nghị lực."),
    "thanh_long": _meta("Thanh Long", "vòng Lộc Tồn", "tốt", "May mắn, hung thần biến thành phúc, vận động."),
    "tieu_hao": _meta("Tiểu Hao", "vòng Lộc Tồn", "xấu", "Hao hao nhỏ, tốn kém, mất mát vặt."),
    "tuong_quan": _meta("Tướng Quân", "vòng Lộc Tồn", "tốt", "Chỉ huy, bản lĩnh, quyết đoán."),
    "tau_thu": _meta("Tấu Thư", "vòng Lộc Tồn", "tốt", "Lời lẽ, tấu trình, công văn, danh tiếng."),
    "phi_liem": _meta("Phi Liêm", "vòng Lộc Tồn", "xấu", "Kiện tụng, thị phi, tai mồm."),
    "hy_than": _meta("Hỷ Thần", "vòng Lộc Tồn", "tốt", "Niềm vui, hỷ sự, may mắn bất ngờ."),
    "benh_phu": _meta("Bệnh Phù", "vòng Lộc Tồn", "xấu", "Bệnh tật, lo âu về sức khỏe."),
    "dai_hao": _meta("Đại Hao", "vòng Lộc Tồn", "xấu", "Hao tổn lớn, tổn thất tài sản."),
    "phuc_binh": _meta("Phục Binh", "vòng Lộc Tồn", "xấu", "Ngầm nguy, phục kích, chuyện sau lưng."),
    # ------------------------- phụ tinh theo Can --------------------------
    "thien_quang": _meta("Thiên Quang", "phụ tinh", "tốt", "Quang minh, may mắn, thông minh hiểu biết."),
    "thien_phuc": _meta("Thiên Phúc", "phụ tinh", "tốt", "Phước lành, trợ lực, may mắn về sau."),
    "luu_ha": _meta("Lưu Hà", "phụ tinh", "xấu", "Che chắn, bế tắc, cản trở."),
    "thien_tru": _meta("Thiên Trù", "phụ tinh", "tốt", "Chốn lương thực, no ấm, sinh kế."),
    "quang_an_can": _meta("Quang Ấn", "phụ tinh", "tốt", "Danh vọng, học vấn, chức tước."),
    "kinh_duong": _meta("Kình Dương", "phụ tinh", "xấu", "Cương, hung, xung khắc, nhanh và mạnh."),
    "da_la": _meta("Đà La", "phụ tinh", "xấu", "Trì trệ, cản trở, dai dẳng, hay kéo dài."),
    "thien_khoi": _meta("Thiên Khôi", "phụ tinh", "tốt", "Quý nhân, văn tinh, trí tuệ, gặp người giúp đỡ."),
    "thien_viet": _meta("Thiên Việt", "phụ tinh", "tốt", "Bàng quang, quý nhân, người che chở."),
    # ------------------------- phụ tinh theo Chi --------------------------
    "long_tri": _meta("Long Trì", "phụ tinh", "tốt", "Uy vọng, danh tiếng, quý nhân."),
    "phuong_cac": _meta("Phượng Các", "phụ tinh", "tốt", "Sang trọng, văn chương, danh dự."),
    "giai_than": _meta("Giải Thần", "phụ tinh", "tốt", "Hoá giải, gỡ vướng, tai qua nạn khỏi."),
    "thien_khoc": _meta("Thiên Khốc", "phụ tinh", "xấu", "Bi ai, tiếng khóc dở, tang lễ."),
    "thien_hu": _meta("Thiên Hư", "phụ tinh", "xấu", "Hư hoại, thành công sớm bại, cô quạnh."),
    "thien_duc": _meta("Thiên Đức", "phụ tinh", "tốt", "Ân đức, may mắn, người giúp."),
    "nguyet_duc": _meta("Nguyệt Đức", "phụ tinh", "tốt", "Phúc đức phụ nữ, tính dịu hiền, hoá giải."),
    "hong_loan": _meta("Hồng Loan", "phụ tinh", "tốt", "Hỷ sự, tình duyên, hôn nhân, tin vui."),
    "thien_hy": _meta("Thiên Hỷ", "phụ tinh", "tốt", "Tin mừng, vui vẻ, hôn nhân."),
    "co_than": _meta("Cô Thần", "phụ tinh", "xấu", "Cô độc, lẻ loi, thiếu người nương."),
    "qua_tu": _meta("Quả Tú", "phụ tinh", "xấu", "Quả phụ, cô quả, thiếu hụt tình thân."),
    "dao_hoa": _meta("Đào Hoa", "phụ tinh", "trung", "Duyên tình, quyến rũ, đào hoa, cũng dễ thị phi."),
    "thien_ma": _meta("Thiên Mã", "phụ tinh", "trung", "Di chuyển, đi lại, thay đổi chỗ ở, năng động."),
    "kiep_sat": _meta("Kiếp Sát", "phụ tinh", "xấu", "Tai ương, kiếp nạn, trộm cướp, thất vọng."),
    "hoa_cai": _meta("Hoa Cái", "phụ tinh", "trung", "Nghệ thuật, độc lập, cô độc, thanh cao."),
    "pha_toai": _meta("Phá Toái", "phụ tinh", "xấu", "Bể vỡ, tan vỡ, hao tán."),
    "thien_khong": _meta("Thiên Không", "phụ tinh", "xấu", "Hư không, trống rỗng, hao hụt, khó bền."),
    # ------------------------- phụ tinh theo Tháng --------------------------
    "ta_phu": _meta("Tả Phù", "phụ tinh", "tốt", "Giúp việc, quý nhân, phù trợ, bạn hiền."),
    "huu_bat": _meta("Hữu Bật", "phụ tinh", "tốt", "Trợ lực, người giúp việc, hậu thuẫn."),
    "thien_hinh": _meta("Thiên Hình", "phụ tinh", "xấu", "Hình phạt, bệnh tật, tai tiếng, khắc."),
    "thien_dieu": _meta("Thiên Diêu", "phụ tinh", "xấu", "Lăng loàn, phóng túng, tai tiếng."),
    "thien_y": _meta("Thiên Y", "phụ tinh", "tốt", "Y tế, chữa lành, quý nhân, bệnh nhẹ."),
    "thien_giai": _meta("Thiên Giải", "phụ tinh", "tốt", "Gỡ rối, hoá giải, may mắn."),
    "dia_giai": _meta("Địa Giải", "phụ tinh", "tốt", "Hoá giải tai nạn, yên ổn, gỡ hoạ."),
    # ------------------------- phụ tinh theo Giờ --------------------------
    "van_xuong": _meta("Văn Xương", "phụ tinh", "tốt",
                       "Văn chương, học vấn, trí tuệ, kiến thức, học hành thành công."),
    "van_khuc": _meta("Văn Khúc", "phụ tinh", "tốt",
                      "Âm nhạc, tài năng, linh hoạt, học thuật, sắc sảo."),
    "thai_phu": _meta("Thai Phụ", "phụ tinh", "tốt", "Bảo bọc, dìu dắt, giúp đỡ."),
    "phong_cao": _meta("Phong Cáo", "phụ tinh", "tốt", "Tin tức, thông tin, công văn, tiếng tốt."),
    "dia_khong": _meta("Địa Không", "phụ tinh", "xấu", "Hư, không, hao tán, biến động."),
    "dia_kiep": _meta("Địa Kiếp", "phụ tinh", "xấu", "Tai kiếp, trộm cướp, mất mát, biến cố."),
    # ------------------------- Hỏa Linh, Thai Toạ, Quang Quý --------------------------
    "hoa_tinh": _meta("Hỏa Tinh", "phụ tinh", "xấu", "Gấp gáp, nóng nảy, tai hoạ bất ngờ; gặp miếu vượng lại thành lực."),
    "linh_tinh": _meta("Linh Tinh", "phụ tinh", "xấu", "Nóng, khó, xung đột; gặp cát tinh giảm nhẹ."),
    "tam_thai": _meta("Tam Thai", "phụ tinh", "tốt", "Quý nhân, thai nghén, sinh nở, tiến thân."),
    "bat_toa": _meta("Bát Tọa", "phụ tinh", "tốt", "Bạn quý, chỗ ngồi cao, nâng đỡ."),
    "an_quang": _meta("Ân Quang", "phụ tinh", "tốt", "Ân điển, quý nhân, phúc lành, cứu giúp."),
    "thien_quy": _meta("Thiên Quý", "phụ tinh", "tốt", "Bảo vật, may mắn, quý nhân."),
    "tuan": _meta("Tuần", "tuần không", "xấu", "Không vận, giai đoạn trống, cản trở."),
    "triet_1": _meta("Triệt", "tuần không", "xấu", "Chặn đứng, che lấp, hao mất, cần thận."),
    "triet_2": _meta("Triệt 2", "tuần không", "xấu", "Chặn đứng, che lấp, giai đoạn khó."),
    "thien_la": _meta("Thiên La", "sao cố định", "xấu", "Mạng lưới, giam hãm, nổi loạn."),
    "dia_vong": _meta("Địa Võng", "sao cố định", "xấu", "Bẫy rập, sa lầy, khó thoát."),
    "thien_thuong": _meta("Thiên Thương", "sao cố định", "xấu", "Tổn thương, đau đớn, thương tổn."),
    "thien_su": _meta("Thiên Sứ", "sao cố định", "xấu", "Sự vụ, tai nạn đến bất ngờ."),
    "dau_quan": _meta("Đẩu Quân", "sao cố định", "trung", "Quân vụ, kỷ luật, quyết đoán."),
    "thien_tai": _meta("Thiên Tài", "sao cố định", "tốt", "Tài năng, kho báu, trí tuệ."),
    "thien_tho": _meta("Thiên Thọ", "sao cố định", "tốt", "Trường thọ, phúc lành, bền bỉ."),
    # ------------------------- Tứ Hoá --------------------------
    "hoa_loc": _meta("Hóa Lộc", "tứ hoá", "tốt", "Sao nhận Lộc; lợi lộc, tài năng, may mắn toả sáng."),
    "hoa_quyen": _meta("Hóa Quyền", "tứ hoá", "tốt", "Sao nhận Quyền; quyền hành, thăng tiến, khống chế."),
    "hoa_khoa": _meta("Hóa Khoa", "tứ hoá", "tốt", "Sao nhận Khoa; danh tiếng, học vấn, nổi bật."),
    "hoa_ky": _meta("Hóa Kỵ", "tứ hoá", "xấu", "Sao nhận Kỵ; ngăn trở, xáo trộn, hao tổn."),
}


# --------------------------------------------------------------------------- #
# Mô tả riêng 14 chính tinh × 12 cung.
# Chỉ số cung: 0=Mệnh, 1=Phụ Mẫu, ..., 11=Huynh Đệ (vị trí TƯƠNG ĐỐI so với Mệnh).
# --------------------------------------------------------------------------- #
DETAIL_MAIN = {
    "tu_vi": {
        0: "Tử Vi thủ Mệnh: người có uy quyền, tự tin, bản lĩnh, được quý mà dễ có chuyện đơn độc vì bề thế.",
        1: "Tử Vi ở Phụ Mẫu: cha mẹ có uy, gia đình nề nếp, được tổ tiên phù trợ.",
        2: "Tử Vi ở Phúc Đức: phúc khí dày, hưởng thụ cao, tinh thần vững nhưng dễ xa rời đời thực.",
        3: "Tử Vi ở Điền Trạch: cơ nghiệp rộng, nhà cửa sang, giữ được đất đai tổ nghiệp.",
        4: "Tử Vi ở Quan Lộc: sự nghiệp có uy, chức quyền, thăng quan phát tài.",
        5: "Tử Vi ở Nô Bộc: được người phục vụ, có cấp dưới hùng hậu, bạn bè phải tôn trọng.",
        6: "Tử Vi ở Thiên Di: ra ngoài được trọng vọng, dễ gặp quý nhân nơi xa.",
        7: "Tử Vi ở Tật Ách: sức khoẻ về già cần chú ý, trước hạn có bệnh nhẹ nhưng dễ chuyển.",
        8: "Tử Vi ở Tài Bạch: tài chính vững, thu nhập ổn định, biết giữ của và làm ăn lớn.",
        9: "Tử Vi ở Tử Tức: con cái có bản lĩnh, hậu vận tốt; nhưng dễ xa con lúc già.",
        10: "Tử Vi ở Phu Thê: hôn nhân có người đứng đắn, tuy nhiên dễ gia trưởng, cần nhịn.",
        11: "Tử Vi ở Huynh Đệ: anh chị em có người ưu tú, được anh em nâng đỡ.",
    },
    "thien_co": {
        0: "Thiên Cơ thủ Mệnh: thông minh, mưu lược, hay suy nghĩ, hợp nghề nghiên cứu hoặc tư vấn.",
        1: "Thiên Cơ ở Phụ Mẫu: cha mẹ khéo lo tính, khó tính trong thời trẻ.",
        2: "Thiên Cơ ở Phúc Đức: tâm trí hoạt động mạnh, thích tìm hiểu, tinh thần không yên.",
        3: "Thiên Cơ ở Điền Trạch: nhà cửa hay thay đổi, dễ bán mua, nên cẩn trọng giấy tờ.",
        4: "Thiên Cơ ở Quan Lộc: nghề nghiệp trí óc, mưu lược, có tài xử lý tình huống.",
        5: "Thiên Cơ ở Nô Bộc: bạn bè thay đổi, có người trí thức giúp đỡ.",
        6: "Thiên Cơ ở Thiên Di: đi xa có kế hoạch, gặp người thông thái.",
        7: "Thiên Cơ ở Tật Ách: lo nghĩ nhiều gây tổn thần, chú ý thần kinh và dạ dày.",
        8: "Thiên Cơ ở Tài Bạch: kiếm tiền bằng đầu óc, có biến động, phải tính toán.",
        9: "Thiên Cơ ở Tử Tức: con cái thông minh, thích học, ít con.",
        10: "Thiên Cơ ở Phu Thê: vợ chồng có người tháo vát, nhưng dễ nghi ngờ dẫn tới buồn phiền.",
        11: "Thiên Cơ ở Huynh Đệ: anh em giỏi giang, có người đi xa, quan hệ đổi thay.",
    },
    "thai_duong": {
        0: "Thái Dương thủ Mệnh: sáng sủa, hào hiệp, có danh, dễ thành công ở chốn công cộng.",
        1: "Thái Dương ở Phụ Mẫu: cha mẹ hiển vinh, số được nhờ công cha.",
        2: "Thái Dương ở Phúc Đức: tinh thần lạc quan, phúc quang minh, hay làm việc thiện.",
        3: "Thái Dương ở Điền Trạch: nhà cửa sáng sủa, đất đai phát triển, dễ mở rộng.",
        4: "Thái Dương ở Quan Lộc: công danh rực rỡ, nghề liên quan công quyền, hành chính.",
        5: "Thái Dương ở Nô Bộc: bạn bè nhiệt tình, có nhóm người hỗ trợ.",
        6: "Thái Dương ở Thiên Di: ra ngoài thành danh, nổi tiếng phương xa.",
        7: "Thái Dương ở Tật Ách: sức khoẻ tốt dẻo dai, cẩn mắt và tim mạch.",
        8: "Thái Dương ở Tài Bạch: thu nhập minh bạch, làm việc công có tiền.",
        9: "Thái Dương ở Tử Tức: con cái sáng sủa, có tương lai, con quý.",
        10: "Thái Dương ở Phu Thê: bạn đời chính trực, tích cực; nữ đóng cung dễ có chuyện chồng con.",
        11: "Thái Dương ở Huynh Đệ: anh em rộng rãi, sống có ích, giúp đỡ nhau.",
    },
    "vu_khuc": {
        0: "Vũ Khúc thủ Mệnh: cương quyết, giỏi làm ăn, kỷ luật, giữ được tiền.",
        1: "Vũ Khúc ở Phụ Mẫu: cha mẹ nghiêm túc, biết lo tiền bạc cho con.",
        2: "Vũ Khúc ở Phúc Đức: chuộng vật chất, làm việc chân tay, phúc nhờ cần cù.",
        3: "Vũ Khúc ở Điền Trạch: nhà đất có giá trị, biết đầu tư, cơ nghiệp tăng.",
        4: "Vũ Khúc ở Quan Lộc: sự nghiệp tài chính, kỹ thuật, quản lý rất hợp.",
        5: "Vũ Khúc ở Nô Bộc: bạn bè có người giỏi công việc, cho mượn tiền kỹ.",
        6: "Vũ Khúc ở Thiên Di: đi xa mưu sinh, làm ăn có tiền.",
        7: "Vũ Khúc ở Tật Ách: sức khoẻ cần chú ý xương khớp, làm việc quá tay.",
        8: "Vũ Khúc ở Tài Bạch: sao tài chính tại cung tài, tiền của vững, hợp buôn bán.",
        9: "Vũ Khúc ở Tử Tức: con cái giỏi nghề, nhưng nghiêm khắc, ít gần gũi.",
        10: "Vũ Khúc ở Phu Thê: vợ chồng lo toan kinh tế, ai giữ tiền rõ ràng dễ cãi.",
        11: "Vũ Khúc ở Huynh Đệ: anh em cần cù, cùng làm ăn hợp, dễ tranh quyền lợi.",
    },
    "thien_dong": {
        0: "Thiên Đồng thủ Mệnh: hiền hoà, dễ gần, hưởng phúc, sống ổn định.",
        1: "Thiên Đồng ở Phụ Mẫu: cha mẹ nhân hậu, bao dung, gia đình êm ấm.",
        2: "Thiên Đồng ở Phúc Đức: an nhàn, thích hưởng thụ, có phước.",
        3: "Thiên Đồng ở Điền Trạch: nhà cửa ấm áp, đất đai nhỏ nhưng thoải mái.",
        4: "Thiên Đồng ở Quan Lộc: nghề ổn định, dịch vụ, chăm sóc, không cạnh tranh gay gắt.",
        5: "Thiên Đồng ở Nô Bộc: bạn bè tử tế, giúp không công.",
        6: "Thiên Đồng ở Thiên Di: đi xa hưởng nhàn, gặp người hiền.",
        7: "Thiên Đồng ở Tật Ách: bệnh nhẹ, dễ khỏi, chú ý đường tiêu hoá.",
        8: "Thiên Đồng ở Tài Bạch: tiền đến dễ, tiêu cũng dễ, cần giữ phúc.",
        9: "Thiên Đồng ở Tử Tức: con cái hiếu thảo, ngoan ngoãn.",
        10: "Thiên Đồng ở Phu Thê: hôn nhân hòa thuận, bạn đời hiền lành.",
        11: "Thiên Đồng ở Huynh Đệ: anh em đoàn kết, tình cảm.",
    },
    "liem_trinh": {
        0: "Liêm Trinh thủ Mệnh: bộc trực, có thủ đoạn, dễ nổi loạn khi gặp sự bất công; hợp nghề pháp luật, nghệ thuật.",
        1: "Liêm Trinh ở Phụ Mẫu: cha mẹ khắt khe, gia đình có biến cố.",
        2: "Liêm Trinh ở Phúc Đức: nội tâm sôi động, dễ bị cám dỗ, tinh thần không dễ an.",
        3: "Liêm Trinh ở Điền Trạch: nhà đất có tranh chấp, sổ sách cẩn thận.",
        4: "Liêm Trinh ở Quan Lộc: dễ thăng dễ giáng, làm luật, cảnh sát, quân đội.",
        5: "Liêm Trinh ở Nô Bộc: bạn bè có người mạnh, dễ kết thù.",
        6: "Liêm Trinh ở Thiên Di: đi xa có nguy cơ tranh chấp, người ngoài bất hoà.",
        7: "Liêm Trinh ở Tật Ách: bệnh nội tiết, máu; giai đoạn cần điều trị.",
        8: "Liêm Trinh ở Tài Bạch: kiếm tiền bằng lương, nghề đặc thù; tiền dễ rủi ro.",
        9: "Liêm Trinh ở Tử Tức: con cái bản chất cương, cần giáo dục kỹ.",
        10: "Liêm Trinh ở Phu Thê: hôn nhân có người nóng tính, cần tiết chế.",
        11: "Liêm Trinh ở Huynh Đệ: anh em có người cứng đầu, dễ xung khắc.",
    },
    "thien_phu": {
        0: "Thiên Phủ thủ Mệnh: trầm ổn, có tài giữ của, làm ăn bền, được tiếng là người đáng tin.",
        1: "Thiên Phủ ở Phụ Mẫu: cha mẹ có cơ nghiệp, vững vàng.",
        2: "Thiên Phủ ở Phúc Đức: phúc dồi dào, tư duy thực dụng, hưởng thụ có chừng.",
        3: "Thiên Phủ ở Điền Trạch: đất đai, nhà cửa nhiều, giỏi giữ tài sản.",
        4: "Thiên Phủ ở Quan Lộc: nghề quản lý, tài chính, ngân hàng, rất chuẩn.",
        5: "Thiên Phủ ở Nô Bộc: bạn bè đáng tin, người cấp dưới dễ sai khiến.",
        6: "Thiên Phủ ở Thiên Di: đi xa có tiền, về xây cơ nghiệp.",
        7: "Thiên Phủ ở Tật Ách: sức khoẻ nhìn chung tốt, có bệnh mạn tính.",
        8: "Thiên Phủ ở Tài Bạch: vốn liếng lớn, tiền của vững, hợp mua bán.",
        9: "Thiên Phủ ở Tử Tức: con cái hiền, hậu vận có tài sản.",
        10: "Thiên Phủ ở Phu Thê: bạn đời thực tế, giữ lửa gia đình.",
        11: "Thiên Phủ ở Huynh Đệ: anh em làm ăn có lợi, biết gìn giữ.",
    },
    "thai_am": {
        0: "Thái Âm thủ Mệnh: nội tâm nhạy cảm, có lòng nhân, tài về tình cảm và học vấn.",
        1: "Thái Âm ở Phụ Mẫu: mẹ hiền, tình cảm gia đình sâu.",
        2: "Thái Âm ở Phúc Đức: tâm linh, nghệ thuật, sống nội tâm.",
        3: "Thái Âm ở Điền Trạch: nhà cửa đẹp, có đất ở phương lành.",
        4: "Thái Âm ở Quan Lộc: nghề văn phòng, giáo dục, y tế, hoạt động ban đêm.",
        5: "Thái Âm ở Nô Bộc: bạn bè nữ giúp đỡ nhiều.",
        6: "Thái Âm ở Thiên Di: đi xa có tài vận nữ, dễ được phụ nữ giúp.",
        7: "Thái Âm ở Tật Ách: bệnh về tâm lý, khí huyết, phụ nữ cần chú ý sức khoẻ sinh sản.",
        8: "Thái Âm ở Tài Bạch: tiền âm thầm đến, hợp kinh doanh nhỏ, nghề nữ.",
        9: "Thái Âm ở Tử Tức: con ngoan, đặc biệt con gái.",
        10: "Thái Âm ở Phu Thê: vợ hiền, tình cảm sâu; nam vợ có nét thùy mị.",
        11: "Thái Âm ở Huynh Đệ: anh em có chiều tình cảm.",
    },
    "tham_lang": {
        0: "Tham Lang thủ Mệnh: thông minh, nhiều ham muốn, có tài nghệ thuật, năng động.",
        1: "Tham Lang ở Phụ Mẫu: cha mẹ bận rộn, đa tài.",
        2: "Tham Lang ở Phúc Đức: thích hưởng thụ, có đào hoa, tình chồng.",
        3: "Tham Lang ở Điền Trạch: nhà cửa hoa lệ, tiêu nhiều cho đất.",
        4: "Tham Lang ở Quan Lộc: nghề thương mại, giải trí, đẹp đẽ.",
        5: "Tham Lang ở Nô Bộc: bạn bè vui vẻ, có người ham chơi.",
        6: "Tham Lang ở Thiên Di: ra ngoài nhiều cơ hội, nhưng dễ sa đà.",
        7: "Tham Lang ở Tật Ách: bệnh dễ phát sinh do ăn chơi, cần kiềm chế.",
        8: "Tham Lang ở Tài Bạch: tiền nhiều nhưng tiêu mạnh, dễ thất lộc.",
        9: "Tham Lang ở Tử Tức: con cái năng động, có tài nhưng cần dạy.",
        10: "Tham Lang ở Phu Thê: hôn nhân có thú vị nhưng dễ ghen, dễ ngoại tình.",
        11: "Tham Lang ở Huynh Đệ: anh em hoạt bát, ham vui.",
    },
    "cu_mon": {
        0: "Cự Môn thủ Mệnh: có khẩu tài, đa mưu, hay lo nghĩ, dễ gặp thị phi.",
        1: "Cự Môn ở Phụ Mẫu: cha mẹ nói nhiều, khó khăn thời trẻ.",
        2: "Cự Môn ở Phúc Đức: nội tâm nhiều trăn trở, thích nghiên cứu.",
        3: "Cự Môn ở Điền Trạch: nhà cửa hay đổi, ồn ào.",
        4: "Cự Môn ở Quan Lộc: nghề luật, báo chí, giáo dục, truyền thông.",
        5: "Cự Môn ở Nô Bộc: bạn bè miệng miệng, có thị phi.",
        6: "Cự Môn ở Thiên Di: đi xa gặp lời thị phi, cần cẩn ngôn.",
        7: "Cự Môn ở Tật Ách: bệnh đường hô hấp, thần kinh.",
        8: "Cự Môn ở Tài Bạch: tiền bạc tranh cãi, hợp nghề miệng lưỡi.",
        9: "Cự Môn ở Tử Tức: con cái hay cãi, nhưng có khẩu tài.",
        10: "Cự Môn ở Phu Thê: vợ chồng hay tranh luận; nên nhường nhịn.",
        11: "Cự Môn ở Huynh Đệ: anh em có ý kiến, cần để thắng.",
    },
    "thien_tuong": {
        0: "Thiên Tướng thủ Mệnh: phong thái, lý trí, giúp đỡ người khác, hợp nghề tư vấn, y, quan.",
        1: "Thiên Tướng ở Phụ Mẫu: cha mẹ chuẩn mực, dìu dắt khéo.",
        2: "Thiên Tướng ở Phúc Đức: tinh thần ổn định, phẩm hạnh.",
        3: "Thiên Tướng ở Điền Trạch: nhà cửa đàng hoàng, có người trông.",
        4: "Thiên Tướng ở Quan Lộc: sự nghiệp gọn gàng, hợp chính trị, đoàn thể.",
        5: "Thiên Tướng ở Nô Bộc: bạn bè giúp đỡ, có người giỏi.",
        6: "Thiên Tướng ở Thiên Di: ra ngoài gặp quý nhân, xây mối.",
        7: "Thiên Tướng ở Tật Ách: bệnh nhẹ, điều trị nhanh.",
        8: "Thiên Tướng ở Tài Bạch: tiền ổn, thích giúp đỡ.",
        9: "Thiên Tướng ở Tử Tức: con cái ngoan, có năng lực.",
        10: "Thiên Tướng ở Phu Thê: vợ chồng lịch sự, hỗ trợ.",
        11: "Thiên Tướng ở Huynh Đệ: anh em chuẩn mực, hòa thuận.",
    },
    "thien_luong": {
        0: "Thiên Lương thủ Mệnh: hiền từ, có phúc, hay giúp người, sống có đạo đức.",
        1: "Thiên Lương ở Phụ Mẫu: cha mẹ phúc hậu, chịu khó.",
        2: "Thiên Lương ở Phúc Đức: sao phúc ở cung phúc: rất tốt, số hưởng phước.",
        3: "Thiên Lương ở Điền Trạch: nhà cửa an lành, có phúc tổ.",
        4: "Thiên Lương ở Quan Lộc: nghề giáo, y, luật, tư pháp, có đức.",
        5: "Thiên Lương ở Nô Bộc: bạn bè đáng tin, hay giúp.",
        6: "Thiên Lương ở Thiên Di: đi xa gặp quý nhân, hoá giải nạn.",
        7: "Thiên Lương ở Tật Ách: có bệnh dễ khỏi, gặp y giỏi.",
        8: "Thiên Lương ở Tài Bạch: tiền vừa phải, dễ mất tiền vì giúp người.",
        9: "Thiên Lương ở Tử Tức: con cái hiếu, có hậu vận.",
        10: "Thiên Lương ở Phu Thê: vợ chồng từ tế, sống lâu.",
        11: "Thiên Lương ở Huynh Đệ: anh em hiếu thuận, giúp đỡ.",
    },
    "that_sat": {
        0: "Thất Sát thủ Mệnh: quyết đoán, mạnh mẽ, dám nghĩ dám làm, dễ nóng và cô độc.",
        1: "Thất Sát ở Phụ Mẫu: cha mẹ có tiếng nhưng xa cách.",
        2: "Thất Sát ở Phúc Đức: tâm tính mạnh, hay lo, không yên.",
        3: "Thất Sát ở Điền Trạch: nhà đất có thay đổi lớn.",
        4: "Thất Sát ở Quan Lộc: sự nghiệp có thể bứt phá; hợp quân, công an, chính trị.",
        5: "Thất Sát ở Nô Bộc: bạn bè mạnh, dễ dẫn dắt hay dễ tổn.",
        6: "Thất Sát ở Thiên Di: đi xa gặp cơ hội lớn nhưng tiềm ẩn rủi ro.",
        7: "Thất Sát ở Tật Ách: dễ tai nạn, chấn thương, cần bảo vệ.",
        8: "Thất Sát ở Tài Bạch: kinh doanh lớn, sóng gió, được nhiều.",
        9: "Thất Sát ở Tử Tức: con cái mạnh mẽ, ít gần gũi.",
        10: "Thất Sát ở Phu Thê: hôn nhân nóng gắt, có người bạn đời độc lập.",
        11: "Thất Sát ở Huynh Đệ: anh em ganh nhau, ai tự lập.",
    },
    "pha_quan": {
        0: "Phá Quân thủ Mệnh: táo bạo, phá cựu lập tân, sống tự do, có sự nghiệp lớn.",
        1: "Phá Quân ở Phụ Mẫu: cha mẹ lăn lộn, đổi thay.",
        2: "Phá Quân ở Phúc Đức: tinh thần bứt phá, dễ có bước ngoặt.",
        3: "Phá Quân ở Điền Trạch: nhà cửa phá rồi xây, dễ mất được.",
        4: "Phá Quân ở Quan Lộc: nghề phiêu lưu, đổi nghề nhiều lần, có dịp thành công lớn.",
        5: "Phá Quân ở Nô Bộc: bạn bè tự do, dễ lợi – dễ mất.",
        6: "Phá Quân ở Thiên Di: đi xa làm ăn táo bạo, cần kế hoạch.",
        7: "Phá Quân ở Tật Ách: dễ chấn thương, đau đớn.",
        8: "Phá Quân ở Tài Bạch: tiền vào nhanh mất nhanh, cẩn đầu tư.",
        9: "Phá Quân ở Tử Tức: con cái tự lập, hay thay đổi.",
        10: "Phá Quân ở Phu Thê: hôn nhân nhiều sóng gió, cần bền lòng.",
        11: "Phá Quân ở Huynh Đệ: anh em phiêu bạt, xa nhau.",
    },
}


# --------------------------------------------------------------------------- #
# Mô tả riêng thêm một số phụ tinh quan trọng (nếu muốn chi tiết thay cho tổng hợp).
# --------------------------------------------------------------------------- #
DETAIL_EXTRA = {
    "loc_ton": {
        0: "Lộc Tồn thủ Mệnh: tâm thiện, giàu lòng, tiền bạc dồi dào, dễ được tăng lộc.",
        1: "Lộc Tồn ở Phụ Mẫu: được cha mẹ cho của, sống no đủ thời trẻ.",
        2: "Lộc Tồn ở Phúc Đức: phúc hưởng lâu, tinh thần an nhiên.",
        3: "Lộc Tồn ở Điền Trạch: cơ nghiệp, nhà đất tốt, giữ được của.",
        4: "Lộc Tồn ở Quan Lộc: có lộc quan, nghề nghiệp phát đạt.",
        5: "Lộc Tồn ở Nô Bộc: bạn bè cho lợi, người giúp.",
        6: "Lộc Tồn ở Thiên Di: đi xa có lộc.",
        7: "Lộc Tồn ở Tật Ách: bệnh nhẹ nhưng lo sợ thái quá.",
        8: "Lộc Tồn ở Tài Bạch: lộc tài, có kho dự phòng, rất tốt.",
        9: "Lộc Tồn ở Tử Tức: con cái phát triển, có tiền gửi.",
        10: "Lộc Tồn ở Phu Thê: vợ chồng có của, có lòng.",
        11: "Lộc Tồn ở Huynh Đệ: anh em san sẻ, có lộc.",
    },
}
